data_dir: ${data_dir}
maxsize: null
nmb_cluster: 2
maxlen: -1
ext: "csv"
datetime: False
gamma: 1.4
Tb: 7e-06
Th: 80
N: 2500
n: 8
start_epoch: 0
epochs: 30
batch: 128
lr: 0.001
momentum: 0.9
wd: 0.0001
seed: 42
workers: 4
device: "cpu"
verbose: True
nruns: 3
type: null
result_path: null