data_dir: ${work_dir}/data/sin_K2_C5/
maxsize: null
nmb_cluster: 3
maxlen: -1
ext: "csv"
not_datetime: True
gamma: 1.4
Tb: 7e-06
Th: 80
N: 2500
n: 8
start_epoch: 0
epochs: 30
batch: 128
lr: 0.001
momentum: 0.9
wd: 0.0001
seed: 42
workers: 4
device: "cpu"
verbose: False
nruns: 3
type: null
result_path: null