test_tube:
    _target_: pytorch_lightning.loggers.test_tube.TestTubeLogger
    save_dir: ${save_dir} #/${aux_module}
    name: ${aux_module}
    version: null
    debug: False
    create_git_tag: False