model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/purity"      # name of the logged metric 
    save_top_k: 1           # save k best models 
    save_last: False         # additionaly save model from last epoch
    period: 5
    mode: "max"             # can be "max" or "min"
    verbose: False
    dirpath: 'checkpoints/'
    filename: '{epoch:02d}'


early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/purity"      # name of the logged metric
    patience: 100           # num of not improving epochs until training stops
    mode: "max"             # can be "max" or "min"
    min_delta: 0            # min change in the logged metric to be qualified as an improvement
