seed: 42
exp_name: default
defaults:
    - datamodule: cohortney_datamodule.yaml #tslearn_datamodule.yaml
    - trainer: default.yaml
    - model: conv1d_autoencoder.yaml
    - callbacks: default.yaml  
    - experiment: null # test_tube.yaml
    - logger: cohortney_logger.yaml # cohortney_logger.yaml # csv_logger.yaml  # test_tube.yaml
    - aux_module: null


n_runs: 10
num_epochs: 50
work_dir: ${hydra:runtime.cwd}
data_name: exp_K2_C5
data_dir: ${work_dir}/data/${data_name}
save_dir: ${work_dir}/experiments/${data_name}
num_clusters: 2
num_events: 5
# path to dictionary with urls to download datasets
data_url_file: ${work_dir}/src/datamodules/datasets_urls.json

# use `python run.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python run.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: True
