_target_: src.datamodules.datamodule.CohortneyDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
maxsize: null
maxlen: -1
ext: "csv"
time_col: "time"
event_col: "event"
datetime: False
batch_size: 128
num_workers: 0
gamma: 1.4
Tb: 7e-06
Th: 80
N: 2500
n: 8
type_: null
