_target_: src.datamodules.datamodule.CohortneyDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
data_url_json: ${data_url_file}
maxsize: 600
maxlen: -1
train_val_split: 0.8
ext: "csv"
time_col: "time"
event_col: "event"
datetime: False
batch_size: 128
num_workers: 8
gamma: 1.4
Tb: 7e-06
Th: 80
N: 2500
n: 8
type_: null
