_target_: src.datamodules.datamodule.TslearnDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
num_clusters: ${num_clusters} # specified in config.yaml
num_events: ${num_events}
maxsize: null
maxlen: 100
ext: "csv"
time_col: "time"
event_col: "event"
batch_size: 128
num_workers: 0
